name: python-env  # Generic name, actual environment name will be specified by command line argument
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
    - poetry>=1.7.1  # Base package management tool
    - poetry-core>=1.8.1  # Core components of poetry
    - poetry-plugin-export>=1.6.0  # Poetry export plugin
